version: "3.9"

services:
  db:
    image: postgres:17.4-bookworm
    ports:
      - "5432:5432"
    command: >
      -c ssl=off
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [acme-network]
    env_file: .env
    user: "postgres:postgres"
    hostname: postgres
    container_name: postgres
    security_opt:
      - label:user:postgres
      - no-new-privileges:true
    cap_drop: [ALL]
    healthcheck:
      test: [CMD, pg_isready, --dbname=postgres, --username=postgres]
      interval: 5s
      timeout: 2s
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 512M

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks: [acme-network]
    env_file: pgadmin.env
    user: "pgadmin:5050"
    hostname: pgadmin
    container_name: pgadmin
    cap_drop: [ALL]
    cap_add: [CHOWN, SETGID, SETUID, DAC_OVERRIDE, NET_BIND_SERVICE]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

volumes:
  postgres_data:
  pgadmin_data:

networks:
  acme-network:
    name: acme-network
