version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4-0
    ports:
      - "8880:8080"
      - "8843:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks: [acme-network]
    env_file: .env
    hostname: keycloak
    container_name: keycloak
    user: keycloak:1000
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    cap_drop: [ALL]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'",
        ]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "2.0"
          memory: 2G

volumes:
  keycloak_data:

networks:
  acme-network:
    name: acme-network
