version: "3.9"

include:
  - path: ../postgres/compose.yml
  - path: ../fakesmtp/compose.yml
  - path: ../keycloak/ci-compose.yml
  
# https://docs.docker.com/compose/compose-file/05-services
services:
  arzt:
    image: yasinayyildiz/arzt:2025.4.1-bookworm
    #image: yasinayyildiz/arzt:2025.4.1-alpine
    depends_on:
      db:
        condition: service_healthy
    ports:
      - published: 3000
        target: 3000
    volumes:
      - type: bind
        source: app.yml
        target: /opt/app/dist/config/resources/app.yml
        read_only: true
      - type: bind
        source: ../../../log
        target: /tmp/log
        read_only: true
      - type: bind
        source: ../../../src/config/resources/tls/key.pem
        target: /opt/app/dist/config/resources/tls/key.pem
        read_only: true
      - type: bind
        source: ../../../src/config/resources/sqlite/arzt.sqlite
        target: /opt/app/dist/config/resources/sqlite/arzt.sqlite
    networks: [acme-network]
    env_file: .env
    #hostname: arzt
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G

networks:
  acme-network:
    name: acme-network
